name: Browser Versions
markdown: kramdown
highlighter: rouge
browsers:
  chrome:
    name: Google Chrome
    link: 'https://www.google.com/intl/en/chrome/'
    version: 51.0.2704.103
    pageid: 19273670
  firefox:
    name: FireFox
    link: 'https://www.mozilla.org/en-US/firefox/new/'
    version: '47.0'
    pageid: 2539503
  ie:
    name: Internet Explorer
    link: 'http://windows.microsoft.com/en-us/internet-explorer/download-ie'
    version: 11.0.28
    pageid: 2607368
  opera:
    name: Opera
    link: 'http://www.opera.com/download'
    version: 38.0.2220.31
    pageid: 2602583
  safari:
    name: Safari
    link: 'http://support.apple.com/downloads/#safari'
    version: 9.1.1
    pageid: 2607326
